import localFont from "next/font/local";
import "./globals.css";
// import App from "next/app";
import AppColors from "@/Generic/AppColors";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const aeonikRegular = localFont({
    src: "./fonts/aeonikRegular.otf",
    variable: "--font-aeonik-regular",
    weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
        style={{backgroundColor: AppColors?.tertiary}}
      >
        {children}
      </body>
    </html>
  );
}
